#!/bin/bash

echo "🏁 Iniciando Forza Garage - Microsserviços"
echo "============================================================"
echo ""

docker compose up --build -d

echo ""
echo "✅ Microsserviços iniciados com sucesso!"
echo ""
echo "📊 Informações dos Serviços:"
echo ""
echo "  🏎️  Garage Service (Microsserviço A):"
echo "      URL: http://localhost:5100"
echo "      Função: Gerenciamento de Inventário"
echo "      Container: garage-service"
echo ""
echo "  📈 Analytics Service (Microsserviço B):"
echo "      URL: http://localhost:5101"
echo "      Função: Relatórios e Análises"
echo "      Container: analytics-service"
echo ""
echo "  🌐 Rede Docker: garage-network"
echo ""
echo "============================================================"
echo ""
echo "🔧 Endpoints Disponíveis:"
echo ""
echo "  Garage Service (5100):"
echo "    • GET  /                    - Info do serviço"
echo "    • GET  /cars                - Listar carros"
echo "    • GET  /cars/<id>           - Buscar carro"
echo "    • POST /cars                - Adicionar carro"
echo "    • PUT  /cars/<id>           - Atualizar carro"
echo "    • DELETE /cars/<id>         - Deletar carro"
echo "    • GET  /stats               - Estatísticas"
echo "    • GET  /health              - Health check"
echo ""
echo "  Analytics Service (5101):"
echo "    • GET  /                    - Info do serviço"
echo "    • GET  /report              - Relatório completo"
echo "    • GET  /report/<id>         - Relatório de um carro"
echo "    • GET  /summary             - Resumo executivo"
echo "    • GET  /activity            - Análise de atividade"
echo "    • GET  /health              - Health check integrado"
echo ""
echo "============================================================"
echo ""
echo "🚀 Comandos Úteis:"
echo ""
echo "  Para ver os logs:"
echo "    ./logs.sh"
echo ""
echo "  Para testar os endpoints:"
echo "    ./test.sh"
echo ""
echo "  Para parar os microsserviços:"
echo "    ./stop.sh"
echo ""
echo "============================================================"
echo ""
echo "💡 Teste rápido:"
echo "  curl http://localhost:5101/summary"
echo ""
